# This file was generated by GoReleaser. DO NOT EDIT.
cask "slapex" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "cb15bf61f40a9ab77d52867e745d546ea6ccc565f81c6a7684dcf085357818eb"
      url "https://github.com/kiyohara/slapex/releases/download/v#{version}/slapex_darwin_amd64"
      binary "slapex_darwin_amd64", target: "slapex"
    end
    on_arm do
      sha256 "2d141fe3a1301cb4cf1d62d6779d1c14657f898d0f56a50cea292246b3238fb1"
      url "https://github.com/kiyohara/slapex/releases/download/v#{version}/slapex_darwin_arm64"
      binary "slapex_darwin_arm64", target: "slapex"
    end
  end

  name "slapex"
  desc "Export Slack channel posts and assets as local static HTML"
  homepage "https://github.com/kiyohara/slapex"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      Dir["#{staged_path}/slapex_darwin_*"].each do |binary|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", binary]
      end
    end
  end

  # No zap stanza required

end
