# This file was generated by GoReleaser. DO NOT EDIT.
cask "slapex" do
  version "1.1.1"

  on_macos do
    on_intel do
      sha256 "152fca6a03eba98cea5c1897f491dc3b61075a592a7ad3c7a1d85cd770e6cbee"
      url "https://github.com/kiyohara/slapex/releases/download/v#{version}/slapex_darwin_amd64"
      binary "slapex_darwin_amd64", target: "slapex"
    end
    on_arm do
      sha256 "2a654e88b376c545537f6a717bb4caa4dbe7663f775dc09151426c1e6590358f"
      url "https://github.com/kiyohara/slapex/releases/download/v#{version}/slapex_darwin_arm64"
      binary "slapex_darwin_arm64", target: "slapex"
    end
  end

  name "slapex"
  desc "Export Slack channel posts and assets as local static HTML"
  homepage "https://github.com/kiyohara/slapex"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      Dir["#{staged_path}/slapex_darwin_*"].each do |binary|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", binary]
      end
    end
  end

  # No zap stanza required

end
