# This file was generated by GoReleaser. DO NOT EDIT.
cask "slapex" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "4ec558200a845ea3d82ad52aef96ebe3a3d503be52c368470bb39d78cf7da996"
      url "https://github.com/kiyohara/slapex/releases/download/v#{version}/slapex_darwin_amd64"
      binary "slapex_darwin_amd64", target: "slapex"
    end
    on_arm do
      sha256 "85bec42b0da24f67feddc80190a0186904ce9993599869d62d19c3e449a792c1"
      url "https://github.com/kiyohara/slapex/releases/download/v#{version}/slapex_darwin_arm64"
      binary "slapex_darwin_arm64", target: "slapex"
    end
  end

  name "slapex"
  desc "Export Slack channel posts and assets as local static HTML"
  homepage "https://github.com/kiyohara/slapex"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      Dir["#{staged_path}/slapex_darwin_*"].each do |binary|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", binary]
      end
    end
  end

  # No zap stanza required

end
